jobs:
  E2E-sql-testing:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('.gradle/*.gradle*', 'build.gradle')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Update Property File
      run: mv src/e2e/resources/test.ci-${{ matrix.browser }}.properties src/e2e/resources/test.properties
    - continue-on-error: true
      name: Run Solr search service + local Datastore emulator
      run: docker-compose up -d
    - continue-on-error: true
      name: Create Config Files
      run: ./gradlew createConfigs testClasses generateTypes
    - continue-on-error: true
      name: Install Frontend Dependencies
      run: npm ci
    - continue-on-error: true
      name: Build Frontend Bundle
      run: npm run build
    - continue-on-error: true
      name: Start Server
      run: './gradlew serverRun &

        ./wait-for-server.sh

        '
    - continue-on-error: true
      name: Start Tests
      run: xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew -P${{ matrix.tests
        }} e2eTestsSql
    strategy:
      fail-fast: false
      matrix:
        browser:
        - firefox
        tests:
        - stable
        - unstable
name: E2E Sql Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-sql.yml
