jobs:
  component-testing:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Update Property File
      run: mv src/test/resources/test.ci-ubuntu-latest.properties src/test/resources/test.properties
    - continue-on-error: true
      name: Run Solr search service
      run: docker-compose run -d -p 8983:8983 solr
    - continue-on-error: true
      name: Run Backend Tests
      run: ./gradlew createConfigs componentTests
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Run Backend Linting
      run: ./gradlew lint --continue
name: Component Tests (JDK 17)
on:
  repository_dispatch:
    types: trigger-ga___jdk17.yml
