jobs:
  check-pr:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: "const pr = await github.rest.pulls.get({\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n  pull_number: context.issue.number\n})\nconst\
          \ isTitleValid = /^\\[#\\d+\\] /.test(pr.data.title)\nconst isDescriptionValid\
          \ = /([Ff]ix(es|ed)?|[Cc]lose(s|d)?|[Rr]esolve(s|d)?|[Pp]art [Oo]f) #\\\
          d+/.test(pr.data.body)\nif (isTitleValid && isDescriptionValid) {\n  return\n\
          }\nlet body = `Hi @${pr.data.user.login}, thank you for your interest in\
          \ contributing to TEAMMATES!\n  However, your PR does not appear to follow\
          \ our [contribution guidelines](https://teammates.github.io/teammates/process.html#step-4-submit-a-pr):\\\
          n\\n`\nif (!isTitleValid) {\n  body += \"- Title must start with the issue\
          \ number the PR is fixing in square brackets, e.g. `[#<issue-number>]`\\\
          n\"\n}\nif (!isDescriptionValid) {\n  body += \"- Description must reference\
          \ the issue number the PR is fixing, e.g. `Fixes #<issue-number>` (or `Part\
          \ of #<issue-number>` if the PR does not address the issue fully)\\n\"\n\
          }\nbody += \"\\nPlease address the above before we proceed to review your\
          \ PR.\"\nawait github.rest.issues.createComment({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body,\n})\n"
name: Pull Request Checker
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
